# Site settings
title: vanessa.is
header-img: img/WestPalm.jpg
description: "Vanessa Calas' blog about tech, startups, millennials, and the global market."
url: "http://vanessa.is"
twitter_username: vanessais_
facebook_username:  vcalas

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Vanessa 
      layout: "post"