# Site settings
title: vanessa.is
header-img: img/WestPalm.jpg
email: va.calas@gmail.com
description: "Vanessa Calas' blog about tech, startups, millennials, and the global market."
url: "http://vanessa.is"
twitter_username: vanessais_
facebook_username:  vcalas

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
